### ISSUE TITLE
Problem with registering and login.

### ISSUE THREAD

**Issue by sherlyc** [EDA-Gurgl/gurgl#151]
Tried to sign up an account for myself, got this error

>  We're sorry, something went wrong while trying to register you! Please try againX

 after i filled up the form and pressed the Add User button.  I run a query with DB, I can see there's a new record from me created in the members table, however I'm unable to login with my password.

**Comment by sherlyc** [comment]
Error logged at the terminal:

Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/Users/Admin/Projects/gurgl/node_modules/jsonwebtoken/sign.js:70:20)
    at createToken (/Users/Admin/Projects/gurgl/server/lib/auth.js:9:14)
    at passport.authenticate (/Users/Admin/Projects/gurgl/server/lib/auth.js:43:21)
    at Strategy.strategy.success (/Users/Admin/Projects/gurgl/node_modules/passport/lib/middleware/authenticate.js:201:18)
    at verified (/Users/Admin/Projects/gurgl/node_modules/passport-local/lib/strategy.js:83:10)
    at users.getByName.then.users (/Users/Admin/Projects/gurgl/server/lib/auth.js:65:7)
    at tryCatcher (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Admin/Projects/gurgl/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)

**Comment by BrenMurrell** [comment]
Hey @sherlyc - this is expected behaviour if the auth hasn't been set up correctly. I had the same issue. see slack for the solution (not going to post the solution here as its a bit too public) - https://gurgl.slack.com/archives/C6Q5EQYE4/p1503111269000083
